name: Deploy Frontend to World4You
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.world4you.com
        username: ftp1382394_deploy
        password: ${{ secrets.FTP_PASSWORD }}
